### ISSUE TITLE
Videos don't play from CouchPotato

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#21]
I am curious how this works with finding out the right path for videos from CouchPotato.

The file is an mkv

I have tried copying the video to /mnt/media like the nginx file says but still no dice.

The log error is
`PHP message: PHP Notice:  Undefined offset: 0 in /var/www/application/includes/MediaModel.php on line 289
PHP message: PHP Notice:  Undefined offset: 0 in /var/www/application/includes/MediaModel.php on line 290" while reading response header from upstream, client: 192.168.40.100, server: , request: "GET /watch/index/tt0063350 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.40.135", referrer: "https://192.168.40.135/info/movie/tt0063350"
2015/06/08 21:26:59 [error] 9311#0: *173 FastCGI sent in stderr: "PHP message: ERROR: Set the TheTVDB API in application/config.php !
PHP message: PHP Warning:  fopen(cache/7f96f2e2b7612c253611c51f7ace1334): failed to open stream: No such file or directory in /var/www/application/includes/MediaModel.php on line 67
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/application/includes/MediaModel.php on line 68
PHP message: PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/application/includes/MediaModel.php on line 69
PHP message: PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/application/includes/MediaModel.php on line 70
PHP message: PHP Notice:  Undefined property: stdClass::$files in /var/www/application/controllers/Watch.php on line 24
PHP message: PHP Notice:  Trying to get property of non-object in /var/www/application/controllers/Watch.php on line 24
PHP message: PHP Warning:  fopen(): Filename cannot be empty in /var/www/application/includes/VideoStream.php on line 27" while reading response header from upstream, client: 192.168.40.100, server: , request: "GET /watch/stream/tt0063350 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.40.135", referrer: "https://192.168.40.135/watch/index/tt0063350"`

**Comment by hazcod** [comment]
The error says `ERROR: Set the TheTVDB API in application/config.php`, fix that and see what errors remain popping up as I see multiple errors.

It looks up the video file via CouchPotato in [/controllers/Watch.php](https://github.com/HazCod/Gunther/blob/master/application/controllers/Watch.php#L48) and [/includes/MediaModel.php](https://github.com/HazCod/Gunther/blob/master/application/includes/MediaModel.php#L174)

**Comment by blindpet** [comment]
I have now also tried with an .mp4, same issue.

I am not sure what TVDB has to do with this, I am trying to watch the downloaded video from the box, not get TVDB info.

**Comment by hazcod** [comment]
I'll check your bug reports when I setup a VM this week. I was kind of forgetting this even existed!

**Comment by blindpet** [comment]
Excellent, it is a great project and I'm back to testing this on the Banana Pi. Trying to put the guide together but I need to make sure users can get it all working before I do.

If there could be some way to specify in the UI where TV and Movies are located that would be a step in the right direction I think.

**Comment by hazcod** [comment]
Why? All media lists are pulled from CP & Sick

**Comment by blindpet** [comment]
I was thinking it would help work around this current issue, I have tested in IE and in Chrome

**Comment by hazcod** [comment]
The only time `/var/www` is hardcoded is for the webdav share, so nope. I will check this week

**Comment by hazcod** [comment]
`I have tried copying the video to /mnt/media like the nginx file says but still no dice.`
This might be your culprit btw. The media file must be in the exact location from both Gunther and CouchPotatos view. It is advised to run Gunther with CP & Sick on the same machine.

For example: Couchpotato will report that file1.mkv is on /mnt/movies/file1.mkv.
Gunther will look at /mnt/movies/file1.mkv

**Comment by blindpet** [comment]
I only moved it when it wasn't playing in the CP location. CP and Sick are running on the same device.

Can you tell me additional steps to reproduce a successful playback?

I am on a Raspberry Pi 2, perhaps that is affecting something?

**Comment by hazcod** [comment]
Ohh, okay, my bad. Could you take a look at the log with the latest version?
(update from git, clear log, try to play a movie)

I'm currently running this on a VM, so no CP/Sick locally. Playing media is the only thing I can't test right now.

**Comment by blindpet** [comment]
Did another test with the updated version, still doesn't work here is the log output

http://pastebin.com/wGUdXWBu

**Comment by hazcod** [comment]
Could you do a `git pull` and post the log output? It will print the movie variable. (the files property is missing from movie)

**Comment by blindpet** [comment]
http://pastebin.com/MHCjxyvQ

**Comment by hazcod** [comment]
~~SickRage~~ CouchPotato doesn't include the path to the local file apparently, strange.

**Comment by blindpet** [comment]
That pastebin was from CP not playing. I can't test SR because the episodes aren't showing up yet ;)

**Comment by hazcod** [comment]
I mean CouchPotato. Have you enabled the 'Manage' thing in CP?  It could be that CP only reports the local files if you enable the Manage section. Try enabling & scanning.

**Comment by blindpet** [comment]
I do have manage enabled now, added the folders and restarted CP. Flushed cache and rescanned in Gunther and get a similar error

http://pastebin.com/k7Ys0TN9

**Comment by hazcod** [comment]
Ahh, I see the problem now. You tried multiple releases, and only the 4th release contains a movie file.
I was blindly using the first in my code.

Will fix this this evening

**Comment by hazcod** [comment]
Fixed in last release! (movies aswell as shows)

**Comment by blindpet** [comment]
Confirmed CP videos playing! SR appears still not working but trying a full restart, refresh

**Comment by hazcod** [comment]
Yay!  I tried here with SR myself, try looking in the logs and seeing if the path exists

**Comment by blindpet** [comment]
Tried restarting and refreshing SickRage, see the other issue, maybe I should open a SR issue instead?

**Comment by blindpet** [comment]
Sorry to bring bad news but a new movie added and downloaded isn't playing, here is the log http://pastebin.com/kQqQjNwv

I did flush cache, update library and restart CP

**Comment by hazcod** [comment]
Hehe, no problem
Does the movie appear as finished in CP? It could not find a valid release
(I can confirm as your log does not mention any video file)

**Comment by blindpet** [comment]
I did have to do a quick library scan in CP, can you make that a button in Gunther's admin area or maybe combine it with the library scan button so it does CP library update and then gunther pulls all the new info? CP api lets you do it: http://192.168.40.135:5050/docs/

**Comment by hazcod** [comment]
Hm, I wonder why the current button would not suffice. It uses `manage.update?full=true`

**Comment by blindpet** [comment]
I think I jumped the gun then, I assumed clicking that button just had Gunther pull the current info from CouchPotato and update its own database, I did not know it forces the update on CP before pulling the data into itself.

**Comment by hazcod** [comment]
Added a quick refresh button in 5567f4ba02698121c10355158a2b9da16a101103.
Untested tough.
