### ISSUE TITLE
Error 1005 SQL Script

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#6]
Again using the mysql -u root -p < setup_database.sql

After commenting out the search_path I get this new error

ERROR 1005(HY000) at line 34: Can't create table 'gunther.#sql-3b0_25' (errno: 150)

**Comment by hazcod** [comment]
Have you pulled the latest version of the script just now?
I changed the serial type to unsigned int auto_increment too.

**Comment by blindpet** [comment]
Ok it seems to be OK now, new issue posted though

**Comment by blindpet** [comment]
This actually didn't get fixed (my previous installation I had modified config.php and the setup_database correctly). I ran the script and still get the 1005 error, I am running the script as root with the syntax above.

**Comment by hazcod** [comment]
I will check this within a few hours on a fresh mysql installation.

**Comment by blindpet** [comment]
Thanks, I tried all the syntax manually and it is definitely the line 32 foreign key line. I found this post which might help http://stackoverflow.com/questions/19135691/mysql-error-1005-hy000-cant-create-table-mydb-clientaddressdetails-frm

**Comment by hazcod** [comment]
Can you try running `CREATE INDEX i_userrole ON users(role);` before running the foreign key declaration?

EDIT: Sec, while I try to solve this

**Comment by hazcod** [comment]
Sorry for the fuzz, it's been a while since I used MySQL. Should be fixed in 73063963e6c3113d218ea1b50ff6ea8b6c34810d

**Comment by blindpet** [comment]
No worries, still having issues though.

set_search path is still giving an error; Uknown system variable, when I comment it out I get a create user error

Operation CREATE User failed for 'gunther'

**Comment by hazcod** [comment]
Hmmm. Are you sure you are using the latest script? I ran this script fine on a new mysql install.

**Comment by blindpet** [comment]
Yep, I deleted the sql script and git pulled.

**Comment by hazcod** [comment]
Alright, Im getting the same error as you now. (NO IDEA why it worked 3 hours ago).
Looking into this :)

**Comment by blindpet** [comment]
Hehe gotta love tech, wish I could be of more help but don't have that much MySQL syntax experience.

**Comment by hazcod** [comment]
EDIT: Just to be sure, have you removed the PostgreSQL part so only the MySQL part is in the script?
Because this is why I got the errors as you described. Be sure to do a `DROP DATABSE gunther;` and `DROP USER gunther;` to start with a clean slate.

**Comment by blindpet** [comment]
I had not before but I just did now and am getting the same error in Line 40.

CREATE USER gunther IDENTIFIED BY 'htpcguides';
GRANT ALL PRIVILEGES ON gunther to gunther;

**Comment by hazcod** [comment]
Have you dropped the database and user? What is the exact error you are getting?

**Comment by blindpet** [comment]
I was only dropping the database and not the user!

I will try adding the postgresql stuff now

**Comment by hazcod** [comment]
Glad I could be of help! I am closing this issue. 
Feel free to open a new one up if anything comes to mind.

(Currently working on movie info page)
